server:
  port: 8081
spring:
  profiles:
    active: dev
  datasource:
    driver-class-nickName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/futures?useUnicode=true&characterEncoding=utf-8
    username: root
    password: huyidao313
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

security:
  basic:
    enable: false
  oauth2:
    resource:
      filter-order: 3

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/*.xml
#    configLocation: classpath:mybatis.xml

logging:
  level:
    org.springframework.security: DEBUG

