spring:
  datasource:
    driver-class-nickName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/futures?useUnicode=true&characterEncoding=utf-8
    username: futures_user
    password: yidao123
  jpa:
    hibernate:
      ddl-auto: update