spring:
  datasource:
    driver-class-nickName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/futures?useUnicode=true&characterEncoding=utf-8
    username: root
    password: huyidao313
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

logging:
  level:
    org.springframework.security: DEBUG