server:
  port: 8081
spring:
  profiles:
    active: prod
  aop:
    auto: true
  #多个数据库
  futuresdb:
    datasource:
      driver-class-nickName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/futures?useUnicode=true&characterEncoding=utf-8
      username: futures_user
      password: futures_123
  klinedb:
      datasource:
        driver-class-nickName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hehe?useUnicode=true&characterEncoding=utf-8
        username: hehe_user
        password: yidao123

security:
  basic:
    enable: false
  oauth2:
    resource:
      filter-order: 3

# Mybatis配置
#mybatis:
#    mapperLocations: classpath:mapper/futures/*.xml
#    configLocation: classpath:mybatis.xml


